#remote_theme: bitbrain/jekyll-dash
remote_theme: pages-themes/hacker@v0.2.0
title: charge2earn
url: https://www.charge2earn.com
author: charge2earn

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"
